import SwiftUI

// Generated by Supernova - do not modify manually
struct AppMeasures {

    static let necessaryMeasure = 10 
    static let referencedMeasure = 40 

    // Other measures

    /// Huehuehue
    static let otherMeasuresUnnecessaryMeasure = 40 
}