import SwiftUI

// Generated by Supernova - do not modify manually
extension View {

    /// Border description
    func borderBorderOutsideOfAllGroups() -> some View {
        return self.border(Color(.sRGB, red: 0/255, green: 130/255, blue: 255/255, opacity: 1), width: 2) 
    }

    // Most amazing borders there are

    /// The most amazing border you'll see in your entire life
    func borderMostAmazingBordersThereAreBorderInsideOfAGroup() -> some View {
        return self.border(Color(.sRGB, red: 16/255, green: 170/255, blue: 183/255, opacity: 1), width: 6) 
    }
}