import SwiftUI

// Generated by Supernova - do not modify manually
extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {

        let 40 = Color(.sRGB, red: 180/255, green: 154/255, blue: 242/255, opacity: 1) 
        let 50 = Color(.sRGB, red: 159/255, green: 120/255, blue: 237/255, opacity: 1) 
        let 60 = Color(.sRGB, red: 135/255, green: 76/255, blue: 230/255, opacity: 1) 
        let 70 = Color(.sRGB, red: 106/255, green: 43/255, blue: 191/255, opacity: 1) 
        let 80 = Color(.sRGB, red: 74/255, green: 28/255, blue: 137/255, opacity: 1) 

        // UI Elements

        let uiElementsPrimary = Color(.sRGB, red: 69/255, green: 137/255, blue: 255/255, opacity: 1) 
        let uiElementsSuccess = Color(.sRGB, red: 0/255, green: 164/255, blue: 84/255, opacity: 1) 
        let uiElementsCritical = Color(.sRGB, red: 210/255, green: 48/255, blue: 49/255, opacity: 1) 
        let uiElementsWarning = Color(.sRGB, red: 227/255, green: 107/255, blue: 0/255, opacity: 1) 
        let uiElementsWhiteBorder = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        /// ⚪️ Use on LIGHT Background
        /// 
        /// ✏️ Dividers, Disabled TIle Borders, Disabled Input Borders
        let uiElementsLightBorderLowContrast = Color(.sRGB, red: 242/255, green: 244/255, blue: 245/255, opacity: 1) 

        /// ⚪️ Use on LIGHT Background
        /// 
        /// ✏️ Dividers, TIle Borders, Input Borders
        let uiElementsLightBorderHighContrast = Color(.sRGB, red: 220/255, green: 224/255, blue: 228/255, opacity: 1) 

        /// ⚫️ Use on DARK Background
        /// 
        /// ✏️ Dividers, Layout structure
        let uiElementsDarkBorderLowContrast = Color(.sRGB, red: 35/255, green: 38/255, blue: 41/255, opacity: 1) 

        /// ⚫️ Use on DARK Background
        /// 
        /// ✏️ Dividers, Input borders, Layout structure
        let uiElementsDarkBorderHighContrast = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 

        // on LIGHT

        /// ⚪️ Use only on LIGHT Background
        /// 
        /// ✏️ Headings
        let onLightForegroundBlack = Color(.sRGB, red: 20/255, green: 22/255, blue: 24/255, opacity: 1) 

        /// ⚪️ Use only on LIGHT Background
        /// 
        /// ✏️ Primary texts, Icons
        let onLightForeground01 = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 

        /// ⚪️ Use only on LIGHT Background
        /// 
        /// ✏️ Secondary texts, Icons
        let onLightForeground02 = Color(.sRGB, red: 134/255, green: 143/255, blue: 152/255, opacity: 1) 

        /// ⚪️ Use only on LIGHT Background
        /// 
        /// ✏️ Placeholders, Disabled texts, Default Icon color if alone
        let onLightForeground03 = Color(.sRGB, red: 159/255, green: 170/255, blue: 180/255, opacity: 1) 

        // on DARK

        let onDarkForegroundWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        let onDarkForeground01 = Color(.sRGB, red: 220/255, green: 224/255, blue: 228/255, opacity: 1) 
        let onDarkForeground02 = Color(.sRGB, red: 134/255, green: 143/255, blue: 152/255, opacity: 1) 
        let onDarkForeground03 = Color(.sRGB, red: 105/255, green: 112/255, blue: 119/255, opacity: 1) 

        // LIGHT

        let lightBackgroundWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        let lightBackground01 = Color(.sRGB, red: 249/255, green: 249/255, blue: 250/255, opacity: 1) 
        let lightBackground02 = Color(.sRGB, red: 242/255, green: 244/255, blue: 245/255, opacity: 1) 
        let lightBackground03 = Color(.sRGB, red: 220/255, green: 224/255, blue: 228/255, opacity: 1) 
        let lightBackgroundPrimary = Color(.sRGB, red: 237/255, green: 245/255, blue: 255/255, opacity: 1) 
        let lightBackgroundCritical = Color(.sRGB, red: 255/255, green: 240/255, blue: 240/255, opacity: 1) 
        let lightBackgroundWarning = Color(.sRGB, red: 255/255, green: 242/255, blue: 232/255, opacity: 1) 

        // DARK

        let darkBackgroundBlack = Color(.sRGB, red: 20/255, green: 22/255, blue: 24/255, opacity: 1) 
        let darkBackground01 = Color(.sRGB, red: 25/255, green: 28/255, blue: 30/255, opacity: 1) 
        let darkBackground02 = Color(.sRGB, red: 35/255, green: 38/255, blue: 41/255, opacity: 1) 
        let darkBackground03 = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 

        // Interactive

        // UI Elements

        let interactiveUiElementsPrimaryDark = Color(.sRGB, red: 15/255, green: 98/255, blue: 254/255, opacity: 1) 
        let interactiveUiElementsPrimaryLight = Color(.sRGB, red: 120/255, green: 169/255, blue: 255/255, opacity: 1) 
        let interactiveUiElementsSuccessDark = Color(.sRGB, red: 0/255, green: 129/255, blue: 65/255, opacity: 1) 
        let interactiveUiElementsSuccessLight = Color(.sRGB, red: 76/255, green: 190/255, blue: 117/255, opacity: 1) 
        let interactiveUiElementsCriticalDark = Color(.sRGB, red: 158/255, green: 33/255, blue: 34/255, opacity: 1) 
        let interactiveUiElementsCriticalLight = Color(.sRGB, red: 247/255, green: 85/255, blue: 86/255, opacity: 1) 
        let interactiveUiElementsWarningDark = Color(.sRGB, red: 186/255, green: 78/255, blue: 0/255, opacity: 1) 
        let interactiveUiElementsWarningLight = Color(.sRGB, red: 255/255, green: 131/255, blue: 43/255, opacity: 1) 
        let interactiveUiElementsDarkBgBorderHighContrastHover = Color(.sRGB, red: 192/255, green: 199/255, blue: 206/255, opacity: 1) 

        // on LIGHT

        let interactiveonLightForeground01Hover = Color(.sRGB, red: 20/255, green: 22/255, blue: 24/255, opacity: 1) 
        let interactiveonLightForeground02Hover = Color(.sRGB, red: 105/255, green: 112/255, blue: 119/255, opacity: 1) 

        // on DARK

        let interactiveonDarkForegroundHover = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // LIGHT

        let interactiveLightBackgroundWhiteHover = Color(.sRGB, red: 242/255, green: 244/255, blue: 245/255, opacity: 1) 
        let interactiveLightBackground01Hover = Color(.sRGB, red: 242/255, green: 244/255, blue: 245/255, opacity: 1) 
        let interactiveLightBackground02Hover = Color(.sRGB, red: 220/255, green: 224/255, blue: 228/255, opacity: 1) 
        let interactiveLightBackgroundPrimaryHover = Color(.sRGB, red: 208/255, green: 226/255, blue: 255/255, opacity: 1) 
        let interactiveLightBackgroundCriticalHover = Color(.sRGB, red: 255/255, green: 214/255, blue: 214/255, opacity: 1) 
        let interactiveLightBackgroundWarningHover = Color(.sRGB, red: 255/255, green: 217/255, blue: 190/255, opacity: 1) 

        // DARK

        let interactiveDarkBackgroundBlackHover = Color(.sRGB, red: 35/255, green: 38/255, blue: 41/255, opacity: 1) 
        let interactiveDarkBackground03Hover = Color(.sRGB, red: 35/255, green: 38/255, blue: 41/255, opacity: 1) 

        // Special

        let specialBlanket = Color(.sRGB, red: 20/255, green: 22/255, blue: 24/255, opacity: 0.4) 

        // OLD

        // Core

        // Primary

        // Primary Interactive

        let oldCorePrimaryPrimaryInteractiveAccentLight = Color(.sRGB, red: 120/255, green: 169/255, blue: 255/255, opacity: 1) 
        let oldCorePrimaryPrimaryInteractiveAccentDark = Color(.sRGB, red: 15/255, green: 98/255, blue: 254/255, opacity: 1) 
        let oldCorePrimaryPrimaryInteractiveCriticalLight = Color(.sRGB, red: 247/255, green: 85/255, blue: 86/255, opacity: 1) 
        let oldCorePrimaryPrimaryInteractiveCriticalDark = Color(.sRGB, red: 158/255, green: 33/255, blue: 34/255, opacity: 1) 
        let oldCorePrimaryPrimaryInteractiveSuccessLight = Color(.sRGB, red: 76/255, green: 190/255, blue: 117/255, opacity: 1) 
        let oldCorePrimaryPrimaryInteractiveSuccessDark = Color(.sRGB, red: 0/255, green: 129/255, blue: 65/255, opacity: 1) 
        let oldCorePrimaryPrimaryInteractiveWarningLight = Color(.sRGB, red: 255/255, green: 131/255, blue: 43/255, opacity: 1) 
        let oldCorePrimaryPrimaryInteractiveWarningDark = Color(.sRGB, red: 186/255, green: 78/255, blue: 0/255, opacity: 1) 

        // Text

        let oldCoreTextWhite01 = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        let oldCoreTextWhite02 = Color(.sRGB, red: 220/255, green: 224/255, blue: 228/255, opacity: 1) 
        let oldCoreTextWhite03 = Color(.sRGB, red: 159/255, green: 170/255, blue: 180/255, opacity: 1) 
        let oldCoreTextWhite04 = Color(.sRGB, red: 134/255, green: 143/255, blue: 152/255, opacity: 1) 
        let oldCoreTextWhite05 = Color(.sRGB, red: 105/255, green: 112/255, blue: 119/255, opacity: 1) 
        let oldCoreTextBlack01 = Color(.sRGB, red: 20/255, green: 22/255, blue: 24/255, opacity: 1) 
        let oldCoreTextBlack02 = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 
        let oldCoreTextBlack03 = Color(.sRGB, red: 105/255, green: 112/255, blue: 119/255, opacity: 1) 
        let oldCoreTextBlack04 = Color(.sRGB, red: 134/255, green: 143/255, blue: 152/255, opacity: 1) 
        let oldCoreTextBlack05 = Color(.sRGB, red: 159/255, green: 170/255, blue: 180/255, opacity: 1) 

        // Icon

        let oldCoreIconWhite01 = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        let oldCoreIconWhite02 = Color(.sRGB, red: 220/255, green: 224/255, blue: 228/255, opacity: 1) 
        let oldCoreIconWhite03 = Color(.sRGB, red: 159/255, green: 170/255, blue: 180/255, opacity: 1) 
        let oldCoreIconWhite04 = Color(.sRGB, red: 134/255, green: 143/255, blue: 152/255, opacity: 1) 
        let oldCoreIconWhite05 = Color(.sRGB, red: 105/255, green: 112/255, blue: 119/255, opacity: 1) 
        let oldCoreIconBlack01 = Color(.sRGB, red: 20/255, green: 22/255, blue: 24/255, opacity: 1) 
        let oldCoreIconBlack02 = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 
        let oldCoreIconBlack03 = Color(.sRGB, red: 105/255, green: 112/255, blue: 119/255, opacity: 1) 
        let oldCoreIconBlack04 = Color(.sRGB, red: 134/255, green: 143/255, blue: 152/255, opacity: 1) 
        let oldCoreIconBlack05 = Color(.sRGB, red: 159/255, green: 170/255, blue: 180/255, opacity: 1) 

        // Input Border

        let oldCoreInputBorderWhite01 = Color(.sRGB, red: 242/255, green: 244/255, blue: 245/255, opacity: 1) 
        let oldCoreInputBorderWhite02 = Color(.sRGB, red: 220/255, green: 224/255, blue: 228/255, opacity: 1) 
        let oldCoreInputBorderWhite03 = Color(.sRGB, red: 192/255, green: 199/255, blue: 206/255, opacity: 1) 
        let oldCoreInputBorderBlack01 = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 

        // Input Background

        let oldCoreInputBackgroundWhite01 = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        let oldCoreInputBackgroundWhite02 = Color(.sRGB, red: 249/255, green: 249/255, blue: 250/255, opacity: 1) 
        let oldCoreInputBackgroundWhite03 = Color(.sRGB, red: 242/255, green: 244/255, blue: 245/255, opacity: 1) 
        let oldCoreInputBackgroundWhite04 = Color(.sRGB, red: 220/255, green: 224/255, blue: 228/255, opacity: 1) 
        let oldCoreInputBackgroundBlack01 = Color(.sRGB, red: 25/255, green: 28/255, blue: 30/255, opacity: 1) 
        let oldCoreInputBackgroundBlack02 = Color(.sRGB, red: 35/255, green: 38/255, blue: 41/255, opacity: 1) 
        let oldCoreInputBackgroundBlack03 = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 
        let oldCoreInputBackgroundBlack04 = Color(.sRGB, red: 78/255, green: 83/255, blue: 88/255, opacity: 1) 

        // Tile Border

        let oldCoreTileBorderWhite01 = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        let oldCoreTileBorderWhite02 = Color(.sRGB, red: 242/255, green: 244/255, blue: 245/255, opacity: 1) 
        let oldCoreTileBorderWhite03 = Color(.sRGB, red: 220/255, green: 224/255, blue: 228/255, opacity: 1) 
        let oldCoreTileBorderBlack01 = Color(.sRGB, red: 35/255, green: 38/255, blue: 41/255, opacity: 1) 
        let oldCoreTileBorderBlack02 = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 

        // Divider

        let oldCoreDividerWhite01 = Color(.sRGB, red: 242/255, green: 244/255, blue: 245/255, opacity: 1) 
        let oldCoreDividerWhite02 = Color(.sRGB, red: 220/255, green: 224/255, blue: 228/255, opacity: 1) 
        let oldCoreDividerBlack01 = Color(.sRGB, red: 35/255, green: 38/255, blue: 41/255, opacity: 1) 
        let oldCoreDividerBlack02 = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 

        // Code

        let oldCodeDirectlyExported = Color(.sRGB, red: 20/255, green: 22/255, blue: 24/255, opacity: 1) 
        let oldCodeKeywords = Color(.sRGB, red: 69/255, green: 137/255, blue: 255/255, opacity: 1) 
        let oldCodeNumbers = Color(.sRGB, red: 0/255, green: 158/255, blue: 158/255, opacity: 1) 
        let oldCodeStrings = Color(.sRGB, red: 210/255, green: 48/255, blue: 49/255, opacity: 1) 
        let oldCodeFunctions = Color(.sRGB, red: 0/255, green: 129/255, blue: 65/255, opacity: 1) 
        let oldCodeMethods = Color(.sRGB, red: 135/255, green: 76/255, blue: 230/255, opacity: 1) 
        let oldCodeControlSymbols = Color(.sRGB, red: 178/255, green: 134/255, blue: 0/255, opacity: 1) 
        let oldCodeCode = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 
        let oldCodeComment = Color(.sRGB, red: 134/255, green: 143/255, blue: 152/255, opacity: 1) 

        // Base

        // White

        /// Same as Primary/white
        let oldBaseWhite0 = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // Grey

        let oldBaseGrey5 = Color(.sRGB, red: 249/255, green: 249/255, blue: 250/255, opacity: 1) 
        let oldBaseGrey10 = Color(.sRGB, red: 242/255, green: 244/255, blue: 245/255, opacity: 1) 
        let oldBaseGrey20 = Color(.sRGB, red: 220/255, green: 224/255, blue: 228/255, opacity: 1) 
        let oldBaseGrey30 = Color(.sRGB, red: 192/255, green: 199/255, blue: 206/255, opacity: 1) 
        let oldBaseGrey40 = Color(.sRGB, red: 159/255, green: 170/255, blue: 180/255, opacity: 1) 
        let oldBaseGrey50 = Color(.sRGB, red: 134/255, green: 143/255, blue: 152/255, opacity: 1) 
        let oldBaseGrey60 = Color(.sRGB, red: 105/255, green: 112/255, blue: 119/255, opacity: 1) 
        let oldBaseGrey70 = Color(.sRGB, red: 78/255, green: 83/255, blue: 88/255, opacity: 1) 
        let oldBaseGrey80 = Color(.sRGB, red: 54/255, green: 58/255, blue: 62/255, opacity: 1) 
        let oldBaseGrey90 = Color(.sRGB, red: 35/255, green: 38/255, blue: 41/255, opacity: 1) 
        let oldBaseGrey95 = Color(.sRGB, red: 25/255, green: 28/255, blue: 30/255, opacity: 1) 

        /// Same as Primary/sn-black
        let oldBaseGrey100 = Color(.sRGB, red: 20/255, green: 22/255, blue: 24/255, opacity: 1) 

        // Blue

        let oldBaseBlue5 = Color(.sRGB, red: 246/255, green: 250/255, blue: 255/255, opacity: 1) 
        let oldBaseBlue10 = Color(.sRGB, red: 237/255, green: 245/255, blue: 255/255, opacity: 1) 
        let oldBaseBlue20 = Color(.sRGB, red: 208/255, green: 226/255, blue: 255/255, opacity: 1) 
        let oldBaseBlue30 = Color(.sRGB, red: 166/255, green: 200/255, blue: 255/255, opacity: 1) 
        let oldBaseBlue40 = Color(.sRGB, red: 120/255, green: 169/255, blue: 255/255, opacity: 1) 
        let oldBaseBlue50 = Color(.sRGB, red: 69/255, green: 137/255, blue: 255/255, opacity: 1) 
        let oldBaseBlue60 = Color(.sRGB, red: 15/255, green: 98/255, blue: 254/255, opacity: 1) 
        let oldBaseBlue70 = Color(.sRGB, red: 0/255, green: 67/255, blue: 206/255, opacity: 1) 
        let oldBaseBlue80 = Color(.sRGB, red: 0/255, green: 45/255, blue: 156/255, opacity: 1) 
        let oldBaseBlue90 = Color(.sRGB, red: 0/255, green: 29/255, blue: 108/255, opacity: 1) 
        let oldBaseBlue95 = Color(.sRGB, red: 0/255, green: 23/255, blue: 90/255, opacity: 1) 
        let oldBaseBlue100 = Color(.sRGB, red: 0/255, green: 17/255, blue: 65/255, opacity: 1) 

        // Green

        let oldBaseGreen5 = Color(.sRGB, red: 234/255, green: 254/255, blue: 239/255, opacity: 1) 
        let oldBaseGreen10 = Color(.sRGB, red: 211/255, green: 254/255, blue: 222/255, opacity: 1) 
        let oldBaseGreen20 = Color(.sRGB, red: 164/255, green: 241/255, blue: 187/255, opacity: 1) 
        let oldBaseGreen30 = Color(.sRGB, red: 127/255, green: 218/255, blue: 155/255, opacity: 1) 
        let oldBaseGreen40 = Color(.sRGB, red: 76/255, green: 190/255, blue: 117/255, opacity: 1) 
        let oldBaseGreen50 = Color(.sRGB, red: 0/255, green: 164/255, blue: 84/255, opacity: 1) 
        let oldBaseGreen60 = Color(.sRGB, red: 0/255, green: 129/255, blue: 65/255, opacity: 1) 
        let oldBaseGreen70 = Color(.sRGB, red: 0/255, green: 96/255, blue: 47/255, opacity: 1) 
        let oldBaseGreen80 = Color(.sRGB, red: 0/255, green: 67/255, blue: 31/255, opacity: 1) 
        let oldBaseGreen90 = Color(.sRGB, red: 0/255, green: 45/255, blue: 18/255, opacity: 1) 
        let oldBaseGreen95 = Color(.sRGB, red: 0/255, green: 37/255, blue: 13/255, opacity: 1) 
        let oldBaseGreen100 = Color(.sRGB, red: 0/255, green: 26/255, blue: 8/255, opacity: 1) 

        // Red

        let oldBaseRed5 = Color(.sRGB, red: 255/255, green: 248/255, blue: 248/255, opacity: 1) 
        let oldBaseRed10 = Color(.sRGB, red: 255/255, green: 240/255, blue: 240/255, opacity: 1) 
        let oldBaseRed20 = Color(.sRGB, red: 255/255, green: 214/255, blue: 214/255, opacity: 1) 
        let oldBaseRed30 = Color(.sRGB, red: 255/255, green: 179/255, blue: 179/255, opacity: 1) 
        let oldBaseRed40 = Color(.sRGB, red: 255/255, green: 132/255, blue: 132/255, opacity: 1) 
        let oldBaseRed50 = Color(.sRGB, red: 247/255, green: 85/255, blue: 86/255, opacity: 1) 

        /// Same as Accent/sn-red
        let oldBaseRed60 = Color(.sRGB, red: 210/255, green: 48/255, blue: 49/255, opacity: 1) 
        let oldBaseRed70 = Color(.sRGB, red: 158/255, green: 33/255, blue: 34/255, opacity: 1) 
        let oldBaseRed80 = Color(.sRGB, red: 113/255, green: 21/255, blue: 22/255, opacity: 1) 
        let oldBaseRed90 = Color(.sRGB, red: 78/255, green: 11/255, blue: 12/255, opacity: 1) 
        let oldBaseRed95 = Color(.sRGB, red: 64/255, green: 7/255, blue: 8/255, opacity: 1) 
        let oldBaseRed100 = Color(.sRGB, red: 49/255, green: 5/255, blue: 5/255, opacity: 1) 

        // Orange

        let oldBaseOrange5 = Color(.sRGB, red: 255/255, green: 248/255, blue: 243/255, opacity: 1) 
        let oldBaseOrange10 = Color(.sRGB, red: 255/255, green: 242/255, blue: 232/255, opacity: 1) 
        let oldBaseOrange20 = Color(.sRGB, red: 255/255, green: 217/255, blue: 190/255, opacity: 1) 
        let oldBaseOrange30 = Color(.sRGB, red: 255/255, green: 183/255, blue: 132/255, opacity: 1) 
        let oldBaseOrange40 = Color(.sRGB, red: 255/255, green: 131/255, blue: 43/255, opacity: 1) 
        let oldBaseOrange50 = Color(.sRGB, red: 227/255, green: 107/255, blue: 0/255, opacity: 1) 
        let oldBaseOrange60 = Color(.sRGB, red: 186/255, green: 78/255, blue: 0/255, opacity: 1) 
        let oldBaseOrange70 = Color(.sRGB, red: 138/255, green: 56/255, blue: 0/255, opacity: 1) 
        let oldBaseOrange80 = Color(.sRGB, red: 94/255, green: 41/255, blue: 0/255, opacity: 1) 
        let oldBaseOrange90 = Color(.sRGB, red: 62/255, green: 26/255, blue: 0/255, opacity: 1) 
        let oldBaseOrange95 = Color(.sRGB, red: 51/255, green: 20/255, blue: 0/255, opacity: 1) 
        let oldBaseOrange100 = Color(.sRGB, red: 35/255, green: 16/255, blue: 0/255, opacity: 1) 

        // Purple

        let oldBasePurple5 = Color(.sRGB, red: 250/255, green: 249/255, blue: 254/255, opacity: 1) 
        let oldBasePurple10 = Color(.sRGB, red: 245/255, green: 242/255, blue: 253/255, opacity: 1) 
        let oldBasePurple20 = Color(.sRGB, red: 227/255, green: 219/255, blue: 250/255, opacity: 1) 
        let oldBasePurple30 = Color(.sRGB, red: 206/255, green: 190/255, blue: 247/255, opacity: 1) 
        let oldBasePurple90 = Color(.sRGB, red: 50/255, green: 16/255, blue: 96/255, opacity: 1) 
        let oldBasePurple95 = Color(.sRGB, red: 41/255, green: 12/255, blue: 81/255, opacity: 1) 
        let oldBasePurple100 = Color(.sRGB, red: 30/255, green: 7/255, blue: 62/255, opacity: 1) 

        // Pink

        let oldBasePink5 = Color(.sRGB, red: 255/255, green: 248/255, blue: 250/255, opacity: 1) 
        let oldBasePink10 = Color(.sRGB, red: 254/255, green: 240/255, blue: 245/255, opacity: 1) 
        let oldBasePink20 = Color(.sRGB, red: 253/255, green: 213/255, blue: 228/255, opacity: 1) 
        let oldBasePink30 = Color(.sRGB, red: 251/255, green: 178/255, blue: 207/255, opacity: 1) 
        let oldBasePink40 = Color(.sRGB, red: 249/255, green: 129/255, blue: 183/255, opacity: 1) 
        let oldBasePink50 = Color(.sRGB, red: 244/255, green: 76/255, blue: 162/255, opacity: 1) 
        let oldBasePink60 = Color(.sRGB, red: 204/255, green: 40/255, blue: 130/255, opacity: 1) 
        let oldBasePink70 = Color(.sRGB, red: 154/255, green: 27/255, blue: 96/255, opacity: 1) 
        let oldBasePink80 = Color(.sRGB, red: 115/255, green: 0/255, blue: 69/255, opacity: 1) 
        let oldBasePink90 = Color(.sRGB, red: 80/255, green: 0/255, blue: 46/255, opacity: 1) 
        let oldBasePink95 = Color(.sRGB, red: 67/255, green: 0/255, blue: 38/255, opacity: 1) 
        let oldBasePink100 = Color(.sRGB, red: 51/255, green: 0/255, blue: 27/255, opacity: 1) 

        // Yellow

        let oldBaseYellow5 = Color(.sRGB, red: 253/255, green: 249/255, blue: 235/255, opacity: 1) 
        let oldBaseYellow10 = Color(.sRGB, red: 252/255, green: 244/255, blue: 214/255, opacity: 1) 
        let oldBaseYellow20 = Color(.sRGB, red: 250/255, green: 221/255, blue: 153/255, opacity: 1) 
        let oldBaseYellow30 = Color(.sRGB, red: 241/255, green: 194/255, blue: 27/255, opacity: 1) 
        let oldBaseYellow40 = Color(.sRGB, red: 210/255, green: 161/255, blue: 6/255, opacity: 1) 
        let oldBaseYellow50 = Color(.sRGB, red: 178/255, green: 134/255, blue: 0/255, opacity: 1) 
        let oldBaseYellow60 = Color(.sRGB, red: 142/255, green: 106/255, blue: 0/255, opacity: 1) 
        let oldBaseYellow70 = Color(.sRGB, red: 104/255, green: 78/255, blue: 0/255, opacity: 1) 
        let oldBaseYellow80 = Color(.sRGB, red: 72/255, green: 55/255, blue: 0/255, opacity: 1) 
        let oldBaseYellow90 = Color(.sRGB, red: 48/255, green: 36/255, blue: 0/255, opacity: 1) 
        let oldBaseYellow95 = Color(.sRGB, red: 38/255, green: 28/255, blue: 0/255, opacity: 1) 
        let oldBaseYellow100 = Color(.sRGB, red: 28/255, green: 21/255, blue: 0/255, opacity: 1) 

        // Teal

        let oldBaseTeal5 = Color(.sRGB, red: 231/255, green: 254/255, blue: 254/255, opacity: 1) 
        let oldBaseTeal10 = Color(.sRGB, red: 205/255, green: 253/255, blue: 253/255, opacity: 1) 
        let oldBaseTeal20 = Color(.sRGB, red: 131/255, green: 241/255, blue: 241/255, opacity: 1) 
        let oldBaseTeal30 = Color(.sRGB, red: 61/255, green: 219/255, blue: 219/255, opacity: 1) 
        let oldBaseTeal40 = Color(.sRGB, red: 0/255, green: 187/255, blue: 187/255, opacity: 1) 
        let oldBaseTeal50 = Color(.sRGB, red: 0/255, green: 158/255, blue: 158/255, opacity: 1) 
        let oldBaseTeal60 = Color(.sRGB, red: 30/255, green: 124/255, blue: 123/255, opacity: 1) 
        let oldBaseTeal70 = Color(.sRGB, red: 0/255, green: 92/255, blue: 92/255, opacity: 1) 
        let oldBaseTeal80 = Color(.sRGB, red: 0/255, green: 65/255, blue: 64/255, opacity: 1) 
        let oldBaseTeal90 = Color(.sRGB, red: 0/255, green: 43/255, blue: 43/255, opacity: 1) 
        let oldBaseTeal95 = Color(.sRGB, red: 0/255, green: 34/255, blue: 34/255, opacity: 1) 
        let oldBaseTeal100 = Color(.sRGB, red: 0/255, green: 25/255, blue: 25/255, opacity: 1) 

        // Huehue

        let huehueSupernovaColor = Color(.sRGB, red: 32/255, green: 76/255, blue: 180/255, opacity: 1) 
        let huehueSupernovaReferencedColor = Color(.sRGB, red: 32/255, green: 76/255, blue: 180/255, opacity: 1) 
    }
}