import SwiftUI

// Generated by Supernova - do not modify manually
extension Gradient {
    
    static let Token = Gradient.TokenGradient()
    
    struct TokenGradient {

        /// Description
        let testGradient12345 = LinearGradient(
            gradient: Gradient(stops: [
                Gradient.Stop(color: Color(.sRGB, red: 164/255, green: 30/255, blue: 190/255, opacity: 1), location: 0),
                Gradient.Stop(color: Color(.sRGB, red: 205/255, green: 128/255, blue: 128/255, opacity: 1), location: 0.5),
                Gradient.Stop(color: Color(.sRGB, red: 115/255, green: 127/255, blue: 216/255, opacity: 1), location: 1),
            ]),
            startPoint: UnitPoint(x: 0.5, y: 0),
            endPoint: UnitPoint(x: 0.5, y: 1) 
        )

        // Hello There

        let helloThereGradientInAGroup = LinearGradient(
            gradient: Gradient(stops: [
                Gradient.Stop(color: Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1), location: 0),
                Gradient.Stop(color: Color(.sRGB, red: 255/255, green: 0/255, blue: 0/255, opacity: 1), location: 0.5),
                Gradient.Stop(color: Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 1), location: 1),
            ]),
            startPoint: UnitPoint(x: 0.5, y: 0),
            endPoint: UnitPoint(x: 0.5, y: 1) 
        )
    }
}