import SwiftUI

// Generated by Supernova - do not modify manually
extension View {  

    /// Radius so corrupt that even the Old Gods get envy around it.
    func borderCorruptRadius() -> some View {
        return self.cornerRadius(8) 
    }

    func borderRadiusWithMightyReferencedCornerRadius() -> some View {
        return self.cornerRadius(40) 
    }

    func borderAnotherReferencedRadius() -> some View {
        return self.cornerRadius(69) 
    }

    // Box

    func borderBoxRadiusInABox() -> some View {
        return self.cornerRadius(69) 
    }

    func borderBoxAnotherRadius() -> some View {
        return self.cornerRadius(12) 
    }
}