import SwiftUI

// Generated by Supernova - do not modify manually
extension View {

    func shadowDropdown() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.12), radius: 16, x: 0, y: 8) 
    }

    func shadowHover() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.08), radius: 8, x: 0, y: 4) 
    }

    // Shadow huehue

    /// Huehuehuehue
    func shadowShadowHuehueShadowInAGroup() -> some View {
        return self.shadow(Color(.sRGB, red: 110/255, green: 192/255, blue: 38/255, opacity: 1), radius: 3, x: 1, y: 2) 
    }
}